### ISSUE TITLE
Migration to helm cloud application 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/cloud#2]
Hello @fuchicorp/devops ,

Delete tf files to migrate our deployments for helm. Deployment Service and other tf files should move to helm template folder

https://github.com/fuchicorp/cloud/blob/f8c1a5aa815f6129ccf6b357d0c2b5b7661f37eb/deployment/terraform/cloud-deployment.tf#L1

**Comment by mcalik77** [comment]
NEED HELP
